### ISSUE TITLE
copy from teable is not working in self hosting 

### ISSUE THREAD

**Issue by mz0in** [teableio/teable#539]
when trying to copy rows or data from table in teable , when self hosting the coping notification is how but taking a couple of second and without coping any data, as example trying to copt from teable to excel sheet

**Comment by tea-artist** [comment]
We are using [this API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) for the copy/paste feature, so it only works behind HTTPS.

related: #506

**Comment by mz0in** [comment]
Thanks , I'm using https , I found that this related to the browser  , it's not working on Safari, while it's working fine with chrome

**Comment by tea-artist** [comment]
I reproduced the problem. Safari 13.1 (Released 2020-03-24) should support this feature though, let me take a look

**Comment by tea-artist** [comment]
fixed for safari ⚡️

**Comment by mz0in** [comment]
Thanks ,this is not fixed for my case with  my M1 running Sonoma 14.5, safari version is 17.5 ,
I also downloaded and installed safari technology preview (Safari 17.4, WebKit 19619.1.6.3) and also t'not working

**Comment by tea-artist** [comment]
Maybe docker hasn't been updated, Have you tried teable.io?

**Comment by mz0in** [comment]
Thanks I confirm , it's working now , seems some cash related issue to docker image build or something ,
